### ISSUE TITLE
please

### ISSUE THREAD

**Issue by irham01** [yoonpatrick3/kpop-api-web#1]
![image](https://user-images.githubusercontent.com/77791484/110838771-70614580-82d5-11eb-9692-e1301f9a016b.png)

Please delete space in output..
example : change 'Full Name' into 'Full_Name'

**Comment by irham01** [comment]
:/

**Comment by yoonpatrick3** [comment]
Sorry, I can fix that if you'd like....

**Comment by yoonpatrick3** [comment]
Why do you need this though? You can make json calls with the spaces...

**Comment by irham01** [comment]
yes.. using Json...

then link https://kpop-api.herokuapp.com/equals?stage_name=Yeji&group=ITZY error???

**Comment by irham01** [comment]
sorry sir, i'm newbie.. :(

**Comment by irham01** [comment]
> Why do you need this though? You can make json calls with the spaces...

can you give me sample for node.js ?
